structureregion:
  low:
    x: 240.5
    y: 89.5
    z: 256.5
    pitch: 0.0
    yaw: 0.0
  high:
    x: 255.5
    y: 98.5
    z: 271.5
    pitch: 0.0
    yaw: 0.0

playregion:
  low:
    x: 208.5
    y: 89.5
    z: 256.5
    pitch: 0.0
    yaw: 0.0
  high:
    x: 223.5
    y: 98.5
    z: 271.5
    pitch: 0.0
    yaw: 0.0

spectatespawn:
  x: 216.5
  y: 100.5
  z: 262.5
  pitch: 0.0
  yaw: 0.0

lobby:
  x: 248.5
  y: 100.5
  z: 262.5
  pitch: 0.0
  yaw: 0.0

teams:
  red:
    name: "Red"
    color:
      RED: 255
      BLUE: 0
      GREEN: 0
    chatcolor: "&c"
    spawn:
      x: 209.5
      y: 90.5
      z: 264.5
      pitch: 0.0
      yaw: -90.0
    generator:
      x: 209.5
      y: 91.5
      z: 259.5
      pitch: 0.0
      yaw: 0.0
    bed:
      x: 208.5
      y: 90.5
      z: 268.5
      pitch: 0.0
      yaw: 0.0
    shop:
      x: 0
      y: 0
      z: 0
    teamshop:
      x: 0
      y: 0
      z: 0
  green:
    name: "Green"
    color:
      RED: 0
      BLUE: 0
      GREEN: 255
    chatcolor: "&2"
    spawn:
      x: 222.5
      y: 90.5
      z: 263.5
      pitch: 0.0
      yaw: 90.0
    generator:
      x: 222.5
      y: 91.5
      z: 268.5
      pitch: 0.0
      yaw: 0.0
    bed:
      x: 223.5
      y: 90.5
      z: 259.5
      pitch: 0.0
      yaw: 0.0
    shop:
      x: 0
      y: 0
      z: 0
    teamshop:
      x: 0
      y: 0
      z: 0

generators:
  emerald1:
    item: "emerald"
    x: 0
    y: 64
    z: 0
  diamond1:
    item: "diamond"
    x: 0
    y: 64
    z: 0

