structureregion:
  low:
    x: 240
    y: 89
    z: 256
  high:
    x: 255
    y: 98
    z: 271

playregion:
  low:
    x: 208
    y: 89
    z: 256
  high:
    x: 223
    y: 98
    z: 271

spectatespawn:
  x: 216
  y: 100
  z: 262

lobby:
  x: 248
  y: 100
  z: 262

teams:
  red:
    name: "Red"
    color:
      ==: Color
      RED: 255
      BLUE: 0
      GREEN: 0
    chatcolor: "&c"
    spawn:
      x: 209
      y: 90
      z: 264
      pitch: -90
      yaw: 0
    generator:
      x: 209
      y: 91
      z: 259
    bed:
      x: 208
      y: 90
      z: 268
    shop:
      x: 0
      y: 0
      z: 0
    teamshop:
      x: 0
      y: 0
      z: 0
  green:
    name: "Green"
    color:
      ==: Color
      RED: 0
      BLUE: 0
      GREEN: 255
    chatcolor: "&2"
    spawn:
      x: 222
      y: 90
      z: 263
      pitch: 90
      yaw: 0
    generator:
      x: 222
      y: 91
      z: 268
    bed:
      x: 223
      y: 90
      z: 259
    shop:
      x: 0
      y: 0
      z: 0
    teamshop:
      x: 0
      y: 0
      z: 0

generators:
  emerald1:
    item: "emerald"
    x: 0
    y: 64
    z: 0
  diamond1:
    item: "diamond"
    x: 0
    y: 64
    z: 0

