structureregion:
  low:
    x: -96.0
    y: 40.0
    z: -96.0
    pitch: 0.0
    yaw: 0.0
  high:
    x: 96.0
    y: 120.0
    z: 96.0
    pitch: 0.0
    yaw: 0.0
playregion:
  low:
    x: 404.0
    y: 40.0
    z: 404.0
    pitch: 0.0
    yaw: 0.0
  high:
    x: 596.0
    y: 120.0
    z: 596.0
    pitch: 0.0
    yaw: 0.0
spectatespawn:
  x: 500.5
  y: 126.0
  z: 500.5
  pitch: 0.0
  yaw: 0.0
lobby:
  x: 0.5
  y: 126.0
  z: 0.5
  pitch: 0.0
  yaw: 0.0
teams:
  red:
    name: Red
    color:
      RED: 255
      BLUE: 0
      GREEN: 0
    chatcolor: '&c'
    spawn:
      x: 421.5
      y: 66.0
      z: 500.5
      pitch: 0.0
      yaw: -90.0
    generator:
      x: 418.5
      y: 65.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    bed:
      x: 434.5
      y: 67.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    shop:
      x: 0
      y: 0
      z: 0
    teamshop:
      x: 0
      y: 0
      z: 0
  green:
    name: Green
    color:
      RED: 0
      BLUE: 0
      GREEN: 255
    chatcolor: '&2'
    spawn:
      x: 579.5
      y: 66.0
      z: 500.5
      pitch: 0.0
      yaw: -270.0
    generator:
      x: 582.5
      y: 65.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    bed:
      x: 566.5
      y: 67.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    shop:
      x: 0
      y: 0
      z: 0
    teamshop:
      x: 0
      y: 0
      z: 0
generators:
  emerald1:
    item: emerald
    x: 0
    y: 64
    z: 0
  diamond1:
    item: diamond
    x: 0
    y: 64
    z: 0
