structureregion:
  low:
    x: -96.0
    y: 40.0
    z: -96.0
    pitch: 0.0
    yaw: 0.0
  high:
    x: 96.0
    y: 120.0
    z: 96.0
    pitch: 0.0
    yaw: 0.0
playregion:
  low:
    x: 404.0
    y: 40.0
    z: 404.0
    pitch: 0.0
    yaw: 0.0
  high:
    x: 596.0
    y: 120.0
    z: 596.0
    pitch: 0.0
    yaw: 0.0
spectatespawn:
  x: 500.5
  y: 126.0
  z: 500.5
  pitch: 0.0
  yaw: 0.0
lobby:
  x: 0.5
  y: 126.0
  z: 0.5
  pitch: 0.0
  yaw: 0.0
teams:
  red:
    name: Red
    color:
      ==: Color
      RED: 255
      BLUE: 0
      GREEN: 0
    chatcolor: '&c'
    spawn:
      x: 421.5
      y: 66.0
      z: 500.5
      pitch: 0.0
      yaw: -90.0
    generator:
      x: 418.5
      y: 65.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    bed:
      x: 434.5
      y: 67.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    shop:
      x: 421.0
      y: 66.0
      z: 494.5
    teamshop:
      x: 0
      y: 0
      z: 0
  green:
    name: Green
    color:
      ==: Color
      RED: 0
      BLUE: 0
      GREEN: 255
    chatcolor: '&2'
    spawn:
      x: 579.5
      y: 66.0
      z: 500.5
      pitch: 0.0
      yaw: -270.0
    generator:
      x: 582.5
      y: 65.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    bed:
      x: 566.5
      y: 67.5
      z: 500.5
      pitch: 0.0
      yaw: 0.0
    shop:
      x: 580.0
      y: 66.0
      z: 506.5
    teamshop:
      x: 0
      y: 0
      z: 0
diamondgens:
  diamond1:
    x: 469.5
    y: 67.0
    z: 471.5
    pitch: 0.0
    yaw: 0.0
  diamond2:
    x: 471.5
    y: 67.0
    z: 531.5
    pitch: 0.0
    yaw: 0.0
  diamond3:
    x: 531.5
    y: 67.0
    z: 529.5
    pitch: 0.0
    yaw: 0.0
  diamond4:
    x: 529.5
    y: 67.0
    z: 469.5
    pitch: 0.0
    yaw: 0.0
emeraldgens:
  emerald1:
    x: 493.5
    y: 71.0
    z: 489.5
    pitch: 0.0
    yaw: 0.0
  emerald2:
    x: 508.5
    y: 71.0
    z: 512.5
    pitch: 0.0
    yaw: 0.0
shopchest:
  x: 16.0
  y: 123.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0

