world: "world"

structureregion:
  low:
    x: -100
    y: 0
    z: -100
  high:
    x: 100
    y: 256
    z: 100

playregion:
  low:
    x: -100
    y: 0
    z: -100
  high:
    x: 100
    y: 256
    z: 100

maxplayersperteam: 4

teams:
  red:
    spawn:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
    generator:
      x: 0
      y: 0
      z: 0
    bed:
      x: 0
      y: 0
      z: 0
  green:
    spawn:
      x: 0
      y: 0
      z: 0
      pitch: 0
      yaw: 0
    generator:
      x: 0
      y: 0
      z: 0
    bed:
      x: 0
      y: 0
      z: 0

generators:
  emerald1:
    item: "emerald"
    x: 0
    y: 64
    z: 0
  diamond1:
    item: "diamond"
    x: 0
    y: 64
    z: 0

